import ExcelJS from 'exceljs';
import { calculateBudgetFinancials } from './calculations';

/**
 * Extracts a clean numeric value from an Excel cell (handles number, formula result, formatted strings like "$ 150.000")
 */
function extractNumericValue(cellValue) {
  if (cellValue === null || cellValue === undefined) return 0;
  if (typeof cellValue === 'number') return cellValue;
  if (typeof cellValue === 'object') {
    // Formula cell: { formula: '...', result: 123 }
    if ('result' in cellValue) {
      return extractNumericValue(cellValue.result);
    }
  }
  if (typeof cellValue === 'string') {
    const cleaned = cellValue.replace(/[^0-9.-]/g, '');
    const num = parseFloat(cleaned);
    return isNaN(num) ? 0 : num;
  }
  return 0;
}

/**
 * Extracts a clean string value from an Excel cell
 */
function extractStringValue(cellValue) {
  if (cellValue === null || cellValue === undefined) return '';
  if (typeof cellValue === 'string') return cellValue.trim();
  if (typeof cellValue === 'object') {
    if ('result' in cellValue) {
      return extractStringValue(cellValue.result);
    }
    if ('richText' in cellValue && Array.isArray(cellValue.richText)) {
      return cellValue.richText.map(t => t.text || '').join('').trim();
    }
  }
  return String(cellValue).trim();
}

/**
 * Parses an Excel (.xlsx) file generated by the system and reconstructs the budget structure.
 * 
 * @param {File|Blob|ArrayBuffer} fileOrBuffer - The uploaded .xlsx file
 * @param {Object} fallbackBudget - Existing budget to preserve client info, settings & space IDs
 * @returns {Promise<Object>} Reconstructed budget object
 */
export async function parseBudgetExcel(fileOrBuffer, fallbackBudget = {}) {
  const workbook = new ExcelJS.Workbook();
  const arrayBuffer = fileOrBuffer instanceof ArrayBuffer
    ? fileOrBuffer
    : await fileOrBuffer.arrayBuffer();

  await workbook.xlsx.load(arrayBuffer);

  // Find sheet 'Presupuesto de Obras' or default to first worksheet
  let worksheet = workbook.getWorksheet('Presupuesto de Obras');
  if (!worksheet) {
    worksheet = workbook.worksheets[0];
  }

  if (!worksheet) {
    throw new Error('El archivo Excel no contiene hojas de cálculo legibles.');
  }

  const existingSpaces = fallbackBudget.spaces || [];
  const parsedSpaces = [];

  let currentSpace = null;
  let spaceIndex = 0;

  worksheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    // Skip initial header / KPI dashboard rows (rows 1 to 7)
    if (rowNumber < 8) return;

    const cellA = extractStringValue(row.getCell(1).value);
    const cellB = extractStringValue(row.getCell(2).value);
    const cellC = extractStringValue(row.getCell(3).value);
    const cellD = extractStringValue(row.getCell(4).value);
    const cellE = row.getCell(5).value;
    const cellF = row.getCell(6).value;
    const cellG = row.getCell(7).value;

    // Check if this row is a Space Header: e.g. "1. RECINTO: GENERAL (Medidas: 3m × 3m × 2.4m)"
    if (cellA.includes('RECINTO:') || cellB.includes('RECINTO:') || /^(\d+[\.\)])\s*RECINTO/i.test(cellA)) {
      const headerText = cellA.includes('RECINTO:') ? cellA : cellB;
      
      // Extract room name (between "RECINTO:" and "(" or end of line)
      let roomName = headerText;
      const recintoMatch = headerText.match(/RECINTO:\s*([^(\n\r]+)/i);
      if (recintoMatch && recintoMatch[1]) {
        roomName = recintoMatch[1].trim();
      }

      // Try to extract dimensions if available: "Medidas: 7m × 3m × 2.4m"
      let length = 3;
      let width = 3;
      let height = 2.4;
      const dimsMatch = headerText.match(/Medidas:\s*([0-9.,]+)m?\s*[×x*]\s*([0-9.,]+)m?\s*[×x*]\s*([0-9.,]+)m?/i);
      if (dimsMatch) {
        length = parseFloat(dimsMatch[1].replace(',', '.')) || length;
        width = parseFloat(dimsMatch[2].replace(',', '.')) || width;
        height = parseFloat(dimsMatch[3].replace(',', '.')) || height;
      } else if (existingSpaces[spaceIndex]) {
        length = existingSpaces[spaceIndex].length || length;
        width = existingSpaces[spaceIndex].width || width;
        height = existingSpaces[spaceIndex].height || height;
      }

      // Find matching existing space to retain ID, doors, windows
      const matchedExisting = existingSpaces.find(s => 
        s.name?.trim().toLowerCase() === roomName.toLowerCase() ||
        roomName.toLowerCase().includes(s.name?.trim().toLowerCase())
      ) || existingSpaces[spaceIndex];

      currentSpace = {
        id: matchedExisting?.id || `space_${Date.now()}_${spaceIndex}`,
        name: matchedExisting?.name || roomName,
        length,
        width,
        height,
        doors: matchedExisting?.doors ?? 1,
        windows: matchedExisting?.windows ?? 1,
        customOpeningArea: matchedExisting?.customOpeningArea ?? 0,
        items: []
      };

      parsedSpaces.push(currentSpace);
      spaceIndex++;
      return;
    }

    // Skip Subtotal rows: e.g. "SUBTOTAL GENERAL:" or "TOTAL COSTO DIRECTO"
    if (
      cellA.toUpperCase().startsWith('SUBTOTAL') || 
      cellB.toUpperCase().startsWith('SUBTOTAL') ||
      cellA.toUpperCase().includes('TOTAL COSTO DIRECTO') ||
      cellB.toUpperCase().includes('TOTAL COSTO DIRECTO')
    ) {
      return;
    }

    // Skip table column headers row
    if (cellA === '#' || cellB === 'Partida / Trabajo' || cellB.toLowerCase().includes('partida')) {
      return;
    }

    // Check if this row is an item: must have a Partida name in Col B and belong to a space
    if (currentSpace && cellB.length > 0) {
      const quantity = Math.max(0, extractNumericValue(cellE));
      const unitPrice = Math.max(0, extractNumericValue(cellF));
      const subtotal = extractNumericValue(cellG) || (quantity * unitPrice);

      // Find existing item if possible to preserve ID and category
      const existingItem = currentSpace.items && currentSpace.id
        ? (existingSpaces.find(s => s.id === currentSpace.id)?.items || []).find(it => 
            it.name?.trim().toLowerCase() === cellB.toLowerCase()
          )
        : null;

      const item = {
        id: existingItem?.id || `item_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
        name: cellB,
        description: cellC || existingItem?.description || '',
        unit: cellD || existingItem?.unit || 'gl',
        unitType: existingItem?.unitType || 'fixed',
        quantity: quantity > 0 ? quantity : (existingItem?.quantity || 1),
        unitPrice: Math.round(unitPrice),
        category: existingItem?.category || 'Pintura y Terminaciones'
      };

      currentSpace.items.push(item);
    }
  });

  if (parsedSpaces.length === 0) {
    throw new Error('No se pudieron reconocer recintos válidos en el archivo Excel.');
  }

  // Calculate financials with imported spaces
  const financialSettings = fallbackBudget.financialSettings || {
    overheadPercent: 0,
    discountPercent: 0,
    applyTax: false,
    taxRate: 19
  };

  const financials = calculateBudgetFinancials(parsedSpaces, financialSettings);

  const importedBudget = {
    ...fallbackBudget,
    client: {
      ...(fallbackBudget.client || {}),
      includesMaterials: fallbackBudget.client?.includesMaterials !== false
    },
    spaces: parsedSpaces,
    financialSettings,
    financials,
    notes: fallbackBudget.notes || ''
  };

  return importedBudget;
}
